package USA_Practice;

import java.util.Scanner;

public class DisariumNumber {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter a number: ");
        int n = sc.nextInt();
        String length_str = Integer.toString(n);
        int length = length_str.length();
        int x = n, sum = 0;
        while (n > 0) {
            int temp = n % 10;
            sum = sum + (int) Math.pow(temp, length);
            length--;
            n = n / 10;
        }
        if (sum == x) {
            System.out.println("True");
        } else {
            System.out.println("False");
        }
    }
}


// two string are given a and b ---> b will be generated by random shuffling a and adding a character to a....
// your task is to find that character
// char x = charAt();
// suma = suma + ascii(uncii)
// sumb = sumb = ascii

// diff = sumb - suma
// char(diff)
// ex: a --> abcd  b --> bdace 
// output --> e

// ex: a --> soha b --> osahm
// output --> m